#!/bin/bash
# ==============================================================================
# RunPod Initialization Script — Phases 3–6 (GPU Required)
# Target: Domain-Specific Fine-Tuning with Doctune
# ==============================================================================
# This script sets up the remote GPU pod for training, alignment, evaluation,
# and deployment. Phase 2 (data curation) can be done locally — see
# setup/local_setup.sh for the local alternative.
# ==============================================================================

set -euo pipefail # Exit on error, unbound variables, and pipe failures

echo "--- Starting RunPod Environment Setup ---"

# 1. Navigate to the persistent storage volume
# RunPod provides a /workspace directory that persists across pod restarts.
# NEVER store datasets or model weights outside of this directory.
# NOTE: This script assumes the doctune repository has already been copied or
# cloned into /workspace/doctune before running. If not, run:
#   git clone <your-repo-url> /workspace/doctune
cd /workspace
mkdir -p /workspace/doctune
cd /workspace/doctune

# 2. Update system packages (just in case the base image is stale)
echo "Updating apt repositories..."
apt-get update -y && apt-get install -y git wget tmux jq

# 3. Install uv (much faster dependency resolution than pip)
echo "Installing uv..."
curl -LsSf https://astral.sh/uv/install.sh | sh
source "$HOME/.local/bin/env" 2>/dev/null || export PATH="$HOME/.local/bin:$PATH"

# 4. Install the doctune training stack from pyproject.toml
# Using -e installs the project in editable mode and resolves all [training]
# extras (transformers, peft, trl, accelerate, datasets, bitsandbytes, mlflow)
# with the version bounds declared in pyproject.toml.
echo "Installing doctune[training] from pyproject.toml..."
uv pip install --system -e ".[training]"

# 5. Install Flash Attention 2
# We use --no-build-isolation to force uv to use the pre-installed PyTorch/CUDA
# environment, which prevents it from taking 45 minutes to compile from scratch.
echo "Compiling and installing Flash Attention 2..."
uv pip install --system flash-attn --no-build-isolation

echo "========================================================================"
echo "Setup Complete! The environment is ready."
echo ""
echo "Hardware check:"
nvidia-smi
echo ""
echo "Next steps:"
echo "  1. Upload your dataset files to this pod (generated by local_setup.sh):"
echo "       scp alignment_dataset.jsonl golden_eval.jsonl user@<pod-ip>:/workspace/doctune/"
echo ""
echo "  2. Set your model ID and run SFT:"
echo "       export MODEL_ID=\"your-hf-model-id\"  # e.g. meta-llama/Llama-3.1-8B"
echo "       python -m doctune.training.train_sft --model-id \$MODEL_ID"
echo ""
echo "  3. Run DPO alignment sweep:"
echo "       python -m doctune.training.train_dpo --model-id \$MODEL_ID"
echo ""
echo "  MLflow UI available at: http://0.0.0.0:5000  (log: /workspace/mlflow.log)"
echo "========================================================================"

# Launch MLflow UI in the background — nohup ensures it survives SSH session termination
nohup mlflow ui --host 0.0.0.0 --port 5000 > /workspace/mlflow.log 2>&1 &
